title: A Hybrid Notification and Alert Retrieval Service
handle: DMTN-165
site_url: https://dmtn-165.lsst.io
date: 2020-12-16
aabstract: |-
  We consider the implications of providing a subset of alert packet contents in
  the alert stream, with the full alert packets available for rate-limited
  retrieval using an identifier included in the "lightweight" alert. This hybrid
  approach would enable much wider dissemination of the complete lightweight
  alert stream, potentially to thousands more users than is possible in the
  current baseline. In turn this "alerts on your laptop" access would allow
  users to conduct more sophisticated filtering and analysis than the current
  Alert Filtering Service, increasing the overall scientific returns of the
  alert stream. Community brokers would still be able to retrieve all of the
  contents of the full alert stream within the 60 second latency window and
  would gain greater control over their ingestion of the bulk alert data.
  Technically, this hybrid system may represent a modest increase in complexity
  over the current baseline but is likely to be more operationally robust.
doi: 10.71929/rubin/2998002
osti_id: 2998002
authors:
- bellme
- nelsons
relationships:
  References:
  - 10.1088/1538-3873/aae904
  - 10.71929/rubin/2586493
  - 10.71929/rubin/2587118
  - 10.71929/rubin/2587200
  - 10.71929/rubin/2997858
