# DOI requirements for Data Preview 1
# Assumes Rubin/NSF/DOE creators.
title: Legacy Survey of Space and Time Data Preview 1
site_url: https://dp1.lsst.io/
date: 2025-06-30
abstract: |-
  The Legacy Survey of Space and Time Data Preview 1 (DP1) is the first release
  of data from the NSF-DOE Vera C. Rubin Observatory. It consists of raw and
  calibrated single-epoch images, co-adds, difference images, detection
  catalogs, and other derived data products. DP1 is based on 1792 science-grade
  optical/near-infrared exposures acquired over 48 distinct nights by the Rubin
  Commissioning Camera, LSSTComCam, on the Simonyi Survey Telescope at the
  Summit Facility on Cerro Pachón, Chile during the first on-sky commissioning
  campaign in late 2024. DP1 covers a total of approximately 15 sq. deg. over
  seven roughly equally-sized non-contiguous fields, each independently observed
  in six broad photometric bands, ugrizy, spanning a range of stellar densities
  and latitudes and overlapping with external reference datasets.
instrument_doi: 10.71929/rubin/2561361
dataset_types:
- abstract: |-
    A collection of calibration datasets such as biases, darks, and flats used
    to construct the data release.
  path: products/calibrations/index.html
  butler:
    name: calibrations
    count: 496
- abstract: Unprocessed images from the LSST Commissioning Camera.
  path: products/images/raw_exposure.html
  butler:
    name: raw
    count: 16125
    format: application/fits
- abstract: |-
    Individual processed and calibrated sky images obtained from a single
    observation with a single filter.
  path: products/images/visit_image.html
  butler:
    name: visit_image
    count: 15972
    format: application/fits
- abstract: Images created by subtracting a template image from a visit image.
  path: products/images/difference_image.html
  butler:
    name: difference_image
    count: 15972
    format: application/fits
- abstract: |-
    The combination of multiple processed, calibrated, and background-
    subtracted images, for a patch of sky, for each of the six filters.
  path: products/images/deep_coadd.html
  butler:
    name: deep_coadd
    count: 2644
    format: application/fits
- abstract: |-
    The combination of processed images with the best seeing, for a patch of
    sky and for each of the six LSST filters. Used to create difference
    images.
  path: products/images/template_coadd.html
  butler:
    name: template_coadd
    count: 2730
    format: application/fits
- abstract: HealSparse property maps for the survey.
  path: products/spmaps/index.html
  butler:
    name: survey property
    alias: deepCoadd_*_consolidated_map_*
    count: 84
    format: HSP
- abstract: Measurements for detected sources in difference images.
  path: products/catalogs/dia_source.html
  butler:
    name: dia_source
    count: 25
    format: application/vnd.apache.parquet
  tap:
    name: DiaSource
    count: 3086404
- abstract: Derived properties for transient and variable objects.
  path: products/catalogs/dia_object.html
  butler:
    name: dia_object
    count: 25
    format: application/vnd.apache.parquet
  tap:
    name: DiaObject
    count: 1089818
- abstract: |-
    Forced measurements in visit and difference images, at the coordinates of
    all DIA objects.
  path: products/catalogs/dia_forced_source.html
  butler:
    name: dia_object_forced_source
    count: 597
    format: application/vnd.apache.parquet
  tap:
    name: ForcedSourceOnDiaObject
    count: 196911566
- abstract: Measurements for detected sources in processed visit images.
  path: products/catalogs/source.html
  butler:
    name: source
    count: 1786
    format: application/vnd.apache.parquet
  tap:
    name: Source
    count: 45565632
- abstract: Detections from deep co-adds.
  path: products/catalogs/object.html
  butler:
    name: object
    count: 29
    format: application/vnd.apache.parquet
  tap:
    name: Object
    count: 2299757
- abstract: |-
    Forced measurements in visit and difference images, at the coordinates of
    all objects.
  path: products/catalogs/forced_source.html
  butler:
    name: object_forced_source
    count: 636
    format: application/vnd.apache.parquet
  tap:
    name: ForcedSource
    count: 268796943
- abstract: Metadata, including dates and filters for every visit.
  path: products/catalogs/visit_table.html
  butler:
    name: visit_table
    count: 1
    format: application/vnd.apache.parquet
  tap:
    name: Visit
    count: 1786
- abstract: Per-detector visit metadata.
  path: products/catalogs/visit_detector_table.htm
  butler:
    name: visit_detector_table
    count: 1
    format: application/vnd.apache.parquet
  tap:
    name: CcdVisit
    count: 16071
- abstract: |-
    Instantaneous physical parameters for moving objects at the time of every
    observation.
  path: products/catalogs/ss_source.html
  butler:
    name: ss_source
    count: 1
    format: application/vnd.apache.parquet
  tap:
    name: SSSource
- abstract: Derived parameters for moving objects.
  path: products/catalogs/ss_object.html
  butler:
    name: ss_object
    count: 1
    format: application/vnd.apache.parquet
  tap:
    name: SSObject
