# DOI requirements for Data Preview 1
# Assumes Rubin/NSF/DOE creators.
title: Legacy Survey of Space and Time Data Preview 1
site_url: https://dp1.lsst.io
date: 2025-06-30
abstract: |
  The Legacy Survey of Space and Time Data Preview 1 (DP1) is the first release
  of data from the NSF-DOE Vera C. Rubin Observatory. It consists of raw and
  calibrated single-epoch images, co-adds, difference images, detection
  catalogs, and other derived data products. DP1 is based on 1792 science-grade
  optical/near-infrared exposures acquired over 48 distinct nights by the
  Rubin Commissioning Camera, LSSTComCam, on the Simonyi Survey Telescope at
  the Summit Facility on Cerro Pachón, Chile during the first on-sky
  commissioning campaign in late 2024. DP1 covers a total of approximately 15
  sq. deg. over seven roughly equally-sized non-contiguous fields, each
  independently observed in six broad photometric bands, ugrizy, spanning a
  range of stellar densities and latitudes and overlapping with external
  reference datasets.
instrument_doi: 10.71929/rubin/2561361
dataset_types:
  # Abstract text will be appended to the parent text.
  # Title will be "Parent Title: raw dataset type"
  # URLs are relative to parent site.
  - butler_name: calibrations
    # calibrations is not a real butler name but a collection of butler
    # dataset types. We are not issuing DOIs for each calibration type.
    # It may be a mistake to issue anything at all for calibrations.
    abstract: |
      A collection of calibration datasets such as biases and flats used to
      construct the data release.
    path: products/calibrations/index.html
  - butler_name: raw
    abstract: |
      Unprocessed images from the LSST Commissioning Camera.
    path: products/images/raw_exposure.html
  - butler_name: visit_image
    abstract: |
      Individual processed and calibrated sky images obtained from a single observation
      with a single filter.
    path: products/images/visit_image.html
  - butler_name: difference_image
    abstract: |
      Images created by subtracting a template image from a visit image.
    path: products/images/difference_image.html
  - butler_name: deep_coadd
    abstract: Deep images generated by combining overlapping visit images.
    path: products/images/deep_coadd.html
  - butler_name: template_coadd
    abstract: |
      Deep images generated by combining overlapping visit images used for difference image creation.
    path: products/images/template_coadd.html
  - butler_name: survey_property_maps
    abstract: HealSparse property maps for the survey.
    path: products/spmaps/index.html
  # These are both parquet files that are available to butler and searchable.
  # tap_name field indicates that they exist as both.
  # catalogs stored in a database and queryable over TAP.
  # A DOI is created for both. They will later be linked together with
  # IsVariantFormOf.
  # Landing page will be the same? Add #butler fragment?
  # Butler name and TAP name differ: object vs Object; object_forced_source vs ForcedSource
  - butler_name: dia_source
    abstract: Detections of sources found in difference images.
    path: products/catalogs/dia_source.html
    tap_name: DiaSource
  - butler_name: dia_object
    abstract: Associated objects found in difference images.
    path: products/catalogs/dia_object.html
    tap_name: DiaObject
  - butler_name: dia_object_forced_source
    abstract: Forced Source Catalog of detections found in difference images.
    path: products/catalogs/dia_forced_source.html
    tap_name: DiaForcedSourceOnDiaObject
  - butler_name: source
    abstract: All detections found in single epoch visit images.
    path: products/catalogs/source.html
    tap_name: Source
  - butler_name: object
    abstract: Detections from deep co-adds.
    path: products/catalogs/object.html
    tap_name: Object
  - butler_name: object_forced_source
    abstract: Measurements of every object in single epoch visit images.
    path: products/catalogs/forced_source.html
    tap_name: ForcedSource
  - butler_name: visit_table
    abstract: Metadata, including dates and filters for every visit.
    path: products/catalogs/visit_table.html
    tap_name: Visit
  - butler_name: visit_detector_table
    abstract: Per-detector visit metadata.
    path: products/catalogs/visit_detector_table.htm
    tap_name: CcdVisit
  - butler_name: ss_source
    abstract: ???
    path: products/catalogs/ss_source.html
    tap_name: SSSource
  - butler_name: ss_object
    abstract: ???
    path: products/catalogs/ss_object.html
    tap_name: SSObject
  # TAP only.
  - tap_name: MPCORB
    abstract: ???
    path: products/catalogs/mpcorb.html
