title: Updated estimates of the Rubin system throughput and expected LSST image depth
handle: PSTN-054
site_url: https://pstn-054.lsst.io
date: 2022-06-21
abstract: |-
  This document presents updated estimates, as of May 2022, of the Rubin system
  throughput and compares them to throughput requirements from the LSST Science
  Requirements Document. In addition, it uses these estimates to forecast LSST's
  median single-visit and co-added image depths for the current (OpSim v2.0)
  baseline LSST cadence simulation: (23.8, 24.5, 24.0, 23.4, 22.7, 22.0) and
  (25.6, 26.9, 26.9, 26.4, 25.6, 24.8) in ugrizy, respectively.  In addition, it
  uses these estimates to forecast LSST's median single-visit and co-added image
  depths for the current baseline LSST cadence simulation. Estimated system
  performance relies on actual measurements of the performance of various system
  hardware components, and on simulations where measurements are still
  unavailable. The updated performance estimates meet all the relevant
  requirements from the LSST Science Requirements Document.  As our knowledge of
  the as-buit system continues to improve, updates to these estimates will
  continue to be provided.
doi: 10.71929/rubin/2584366
osti_id: 2584366
authors:
- biancofb
- jonesrl
- ivezicv
- ritzs
- PST
relationships:
  References:
  - 10.1093/mnras/sty2595
  - 10.1117/12.2056898
  - 10.1117/12.2232947
  - 10.1117/12.2233630
  - 10.3847/1538-3881/aae316
  - 10.3847/1538-3881/aafece
  - 10.3847/1538-4357/ab042c
  - 10.3847/1538-4365/ac3e72
  - 10.71929/rubin/2584276
