title: Rubin Observatory Processing of Gravitational Wave TOO Data in the Early Operations Era
handle: RTN-008
site_url: https://rtn-008.lsst.io
date: 2022-08-03
abstract: |-
  Since the watershed discovery of an electromagnetic counterpart to the
  LIGO/VIRGO gravitational wave source GW170817, multi-messenger astrophysics
  has emerged as a major area of strategic focus for the NSF. Rubin
  Observatory’s depth, survey speed, and data management systems will make it a
  key asset in the search for EM counterparts. Exploiting this capability during
  the phases of Rubin commissioning and early operations that coincide with GW
  observing run O4 may require special actions, however. We discuss potential
  approaches to data access, template building, and special data processing.
doi: 10.71929/rubin/2997564
osti_id: 2997564
authors:
- bellme
relationships:
  References:
  - 10.1093/mnras/stab3141
  - 10.1093/mnras/stab872
  - 10.1093/mnras/stz3457
  - 10.1103/PhysRevLett.119.161101
  - 10.3847/1538-4357/abc335
  - 10.3847/1538-4357/ac366d
  - 10.3847/1538-4357/ac4d34
  - 10.3847/1538-4365/ac617c
  - 10.3847/2041-8213/aa91c9
  - 10.3847/2041-8213/aa920c
  - 10.48550/arXiv.1812.04051
  - 10.71929/rubin/2584021
