title: Source Selection for Abell 360 in LSSTComCam Data Preview 1
handle: SITCOMTN-163
site_url: https://sitcomtn-163.lsst.io
abstract: |-
  We cover the source selection done for the Abell 360 LSSTComCam cluster study
  focusing on color and photo-z cuts. Identification of cluster members via the
  red sequence and photo-z offers a science focused validation of photometry
  with LSSTComCam. We are able to cross-match with DESI spectroscopic redshifts
  to offer an independent validation suite on photo-z estimates. We make
  various color and photo-z cuts to generate N(z)s and shear profiles. We find
  that both cuts are quite robust to various choices made and can produce a
  shear profile for Abell 360. Both methods should be applicable to generating
  a consistent mass estimate for the cluster.
date: 2025-06-25
doi: 10.71929/rubin/2571157
osti_id: 2571157
authors:
- adarip
- lindena
relationships:
  References:
  - 10.1086/421365
  - 10.1086/308947
  - 10.48550/arXiv.2503.14745
  - 10.1016/j.ascom.2019.100362
  - 10.5281/zenodo.5683848
  - 10.1214/16-AOAS1013
  - 10.1051/0004-6361:20066601
  - 10.1093/mnras/stad3895
  - 10.1093/pasj/psac006
  - 10.1111/j.1365-2966.2005.09946.x
  - 10.5281/zenodo.7927358
  - 10.21105/astro.2303.03947
  - 10.1093/mnras/stt574
  - 10.3847/1538-3881/accff8
  - 10.3847/1538-4365/abd023
  - 10.1046/j.1365-8711.2003.06683.x
  - 10.1093/mnras/sty2420
  - 10.1093/pasj/psx130
  - 10.1093/pasj/psx130
  - 10.71929/rubin/2570536
  - 10.1086/192122
  - 10.3847/1538-3881/acb213
  - 10.71929/RUBIN/2561361
  - 10.3847/1538-3881/aca5fb
  - 10.71929/rubin/2570325
