title: Rubin Observatory Baseline Calibration Plan
handle: SITCOMTN-086
site_url: https://sitcomtn-086.lsst.io
abstract: |-
  Baseline calibration plan describing the as-built system to be delivered at
  the time of the Operations Readiness Review (ORR), and for use during Year 1
  of the Rubin Observatory Legacy Survey of Space and Time (LSST).
doi: 10.71929/rubin/2583850
osti_id: 2583850
date: 2025-06-12
authors:
- fagreliusp
- rykoffe
relationships:
  References:
  - 10.1051/0004-6361/201935508
  - 10.1086/117915
  - 10.1088/1538-3873/aa858e
  - 10.1088/1538-3873/ad3aa2
  - 10.1117/12.366388
  - 10.3847/1538-3881/aa9f22
  - 10.48550/arXiv.2001.03223
  - 10.48550/arXiv.2305.01695
  - PURL:https://purl.stanford.edu/jy639yg0904
