title: Calculating LSST limiting magnitudes and SNR
handle: SMTN-002
site_url: https://smtn-002.lsst.io/
date: 2021-05-07
abstract: |-
  This technote documents the various m5 calculation tools and provides some
  summary information to facilitate calculating SNR and m5 values. The
  throughput curves used for this analysis are from v1.9 of the
  syseng_throughput repo, which includes the "triple silver" mirror coatings,
  and as-measured mirror, filter and lens throughputs.
doi: 10.71929/rubin/3408482
osti_id: 3408482
authors:
- jonesrl
relationships:
  Cites:
  - 10.3847/1538-4357/ab042c
  - 10.71929/rubin/2584366
