title: On Recruiting
handle: SQR-081
site_url: https://sqr-081.lsst.io
abstract: |-
  An editorial on how we hire and why.
date: 2023-09-20
doi: 10.71929/rubin/2574487
osti_id: 2574487
authors:
- economouf
